import argparse
import os
import numpy as np
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import roc_auc_score


def load_stress_scores(path):
    df = pd.read_csv(path)
    required = {'subject', 'anomaly_score'}
    missing = required - set(df.columns)
    if missing:
        raise ValueError(f"Stress-score file is missing columns: {sorted(missing)}")

    if 'window_start_sec' not in df.columns:
        # Fall back to an index-based pseudo-time if explicit window timing is unavailable.
        df = df.copy()
        df['window_start_sec'] = np.arange(len(df), dtype=float)

    return df


def aggregate_stress(stress_df, bin_size_sec=300):
    stress_df = stress_df.copy()
    stress_df['time_bin'] = (stress_df['window_start_sec'] // bin_size_sec).astype(int)

    p90_threshold = stress_df.groupby('subject')['anomaly_score'].transform(lambda s: s.quantile(0.9))
    stress_df['high_pressure_flag'] = (stress_df['anomaly_score'] >= p90_threshold).astype(int)

    grouped = stress_df.groupby(['subject', 'time_bin'])
    agg = grouped['anomaly_score'].agg(['mean', 'std', 'max']).reset_index()
    agg = agg.rename(
        columns={
            'mean': 'stress_mean',
            'std': 'stress_std',
            'max': 'stress_max',
        }
    )

    pressure_share = grouped['high_pressure_flag'].mean().reset_index(name='high_pressure_share')
    agg = agg.merge(pressure_share, on=['subject', 'time_bin'], how='left')
    agg['stress_std'] = agg['stress_std'].fillna(0.0)
    return agg


def normalize_kpi_timebin(kpi_df, bin_size_sec):
    kpi_df = kpi_df.copy()

    if 'time_bin' in kpi_df.columns:
        kpi_df['time_bin'] = kpi_df['time_bin'].astype(int)
        return kpi_df

    if 'window_start_sec' in kpi_df.columns:
        kpi_df['time_bin'] = (kpi_df['window_start_sec'] // bin_size_sec).astype(int)
        return kpi_df

    if 'timestamp_sec' in kpi_df.columns:
        kpi_df['time_bin'] = (kpi_df['timestamp_sec'] // bin_size_sec).astype(int)
        return kpi_df

    raise ValueError(
        "KPI file must contain one of: 'time_bin', 'window_start_sec', or 'timestamp_sec'."
    )


def correlation_table(merged_df, outcome_columns):
    rows = []
    stress_cols = ['stress_mean', 'stress_std', 'stress_max', 'high_pressure_share']

    for out_col in outcome_columns:
        for stress_col in stress_cols:
            if out_col not in merged_df.columns:
                continue
            valid = merged_df[[out_col, stress_col]].dropna()
            if len(valid) < 5:
                corr_val = np.nan
            else:
                corr_val = valid[out_col].corr(valid[stress_col])
            rows.append(
                {
                    'outcome': out_col,
                    'stress_feature': stress_col,
                    'pearson_corr': corr_val,
                    'n_samples': len(valid),
                }
            )

    return pd.DataFrame(rows)


def binary_auc_table(merged_df, outcome_columns):
    rows = []
    features = ['stress_mean', 'stress_std', 'stress_max', 'high_pressure_share']

    for out_col in outcome_columns:
        if out_col not in merged_df.columns:
            continue

        valid = merged_df[features + [out_col]].dropna()
        y = valid[out_col].to_numpy()

        # Use logistic AUC only for binary targets.
        unique = np.unique(y)
        if len(unique) != 2 or len(valid) < 20:
            continue

        X = valid[features].to_numpy()
        model = LogisticRegression(max_iter=300)
        model.fit(X, y)
        probs = model.predict_proba(X)[:, 1]
        auc_value = roc_auc_score(y, probs)

        rows.append(
            {
                'outcome': out_col,
                'auc_logistic': auc_value,
                'n_samples': len(valid),
            }
        )

    return pd.DataFrame(rows)


def main():
    parser = argparse.ArgumentParser(
        description='Link physiological stress indices with supply-chain KPI outcomes.'
    )
    parser.add_argument(
        '--stress-scores',
        default='results/cv_window_scores.csv',
        help='Path to stress score windows CSV generated by src/models/train.py',
    )
    parser.add_argument(
        '--kpi-file',
        required=True,
        help='Path to operational KPI CSV with subject and time reference columns.',
    )
    parser.add_argument(
        '--outcomes',
        nargs='+',
        required=True,
        help='Outcome columns to evaluate (e.g., defect_rate delay_flag cycle_time).',
    )
    parser.add_argument(
        '--bin-size-sec',
        type=int,
        default=300,
        help='Aggregation window for stress scores before linkage.',
    )
    parser.add_argument(
        '--output-dir',
        default='results',
        help='Directory for output linkage reports.',
    )
    args = parser.parse_args()

    stress_df = load_stress_scores(args.stress_scores)
    stress_agg = aggregate_stress(stress_df, bin_size_sec=args.bin_size_sec)

    kpi_df = pd.read_csv(args.kpi_file)
    if 'subject' not in kpi_df.columns:
        raise ValueError("KPI file must include a 'subject' column.")
    kpi_df['subject'] = kpi_df['subject'].astype(str)
    kpi_df = normalize_kpi_timebin(kpi_df, bin_size_sec=args.bin_size_sec)

    merged = stress_agg.merge(kpi_df, on=['subject', 'time_bin'], how='inner')
    if merged.empty:
        raise ValueError(
            'No overlap found between stress bins and KPI bins. Check subject IDs and time columns.'
        )

    os.makedirs(args.output_dir, exist_ok=True)

    merged_path = os.path.join(args.output_dir, 'stress_kpi_merged.csv')
    corr_path = os.path.join(args.output_dir, 'stress_kpi_correlations.csv')
    auc_path = os.path.join(args.output_dir, 'stress_kpi_binary_auc.csv')

    merged.to_csv(merged_path, index=False)

    corr_df = correlation_table(merged, args.outcomes)
    corr_df.to_csv(corr_path, index=False)

    auc_df = binary_auc_table(merged, args.outcomes)
    auc_df.to_csv(auc_path, index=False)

    print('Linkage analysis complete.')
    print(f'- Merged dataset: {merged_path}')
    print(f'- Correlation table: {corr_path}')
    print(f'- Binary logistic AUC table: {auc_path}')


if __name__ == '__main__':
    main()
